In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Iris.csv")

In [3]:
x = data.iloc[:,1:-1].values
y = data.iloc[:,-1].values

In [4]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [5]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [6]:
lb = LabelEncoder()

In [7]:
y=lb.fit_transform(y)

In [8]:
y = y.reshape((len(y),1))

In [9]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [10]:
ohc = OneHotEncoder(categorical_features=[0],sparse=False)

In [4]:
y=ohc.fit_transform(y)

NameError: name 'ohc' is not defined

In [12]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [13]:
import tensorflow.keras as keras

In [14]:
model = keras.models.Sequential()

In [15]:
model.add(keras.layers.Dense(4))
model.add(keras.layers.Dense(5))
model.add(keras.layers.Dense(3))
model.add(keras.layers.Dense(3,activation='softmax'))

In [27]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [28]:
model.fit(x,y,batch_size=64,epochs=100)

Epoch 1/100
150/150 [==============================] - 0s 3ms/step - loss: 0.5846 - acc: 0.6867
Epoch 2/100
150/150 [==============================] - 0s 73us/step - loss: 0.5755 - acc: 0.6933
Epoch 3/100
150/150 [==============================] - 0s 100us/step - loss: 0.5678 - acc: 0.6933
Epoch 4/100
150/150 [==============================] - 0s 60us/step - loss: 0.5606 - acc: 0.6933
Epoch 5/100
150/150 [==============================] - 0s 60us/step - loss: 0.5531 - acc: 0.7000
Epoch 6/100
150/150 [==============================] - 0s 53us/step - loss: 0.5459 - acc: 0.7133
Epoch 7/100
150/150 [==============================] - 0s 73us/step - loss: 0.5388 - acc: 0.7200
Epoch 8/100
150/150 [==============================] - 0s 80us/step - loss: 0.5321 - acc: 0.7200
Epoch 9/100
150/150 [==============================] - 0s 73us/step - loss: 0.5257 - acc: 0.7200
Epoch 10/100
150/150 [==============================] - 0s 53us/step - loss: 0.5195 - acc: 0.7200
Epoch 11/100
150/150 [=======

In [23]:
sample = x[56]

In [24]:
import numpy as np

In [25]:

sample = np.asarray([sample])

In [26]:
np.round(model.predict(sample))

array([[0., 0., 1.]], dtype=float32)

In [31]:
acc = model.evaluate(x,y)[1]

150/150 [==============================] - 0s 53us/step


In [32]:
acc

0.98